# Generated by Django 6.0.5 on 2026-06-22 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_creator_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['level', 'name'], 'verbose_name': 'Категория объекта', 'verbose_name_plural': 'Категории'},
        ),
    ]
