# Generated by Django 6.0.5 on 2026-07-12 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='creator_id',
            new_name='creator',
        ),
    ]
