# Generated by Django 6.0.5 on 2026-06-11 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(0, 'L0'), (1, 'L1'), (2, 'L2'), (3, 'L3'), (4, 'L4')], verbose_name='Уровень автоматизации')),
                ('system_class', models.CharField(max_length=255, verbose_name='Класс системы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Класс автоматизации',
                'verbose_name_plural': 'Классы автоматизации',
            },
        ),
        migrations.CreateModel(
            name='AutomatedSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autosystem_name', models.CharField(max_length=255, verbose_name='Название системы')),
                ('system_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='systems', to='system.automationclass', verbose_name='Класс системы')),
            ],
            options={
                'verbose_name': 'Автоматизированная система',
                'verbose_name_plural': 'Автоматизированные системы',
            },
        ),
    ]
