# Generated by Django 6.0.5 on 2026-07-02 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(0, 'L0'), (1, 'L1'), (2, 'L2'), (3, 'L3'), (4, 'L4')], verbose_name='Уровень автоматизации')),
                ('system_class', models.CharField(max_length=255, verbose_name='Класс системы')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Класс автоматизации',
                'verbose_name_plural': 'Классы автоматизации',
            },
        ),
        migrations.CreateModel(
            name='VendorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Название продукта')),
            ],
            options={
                'verbose_name': 'Продукт вендора',
                'verbose_name_plural': 'Продукты вендоров',
                'ordering': ['product_name'],
            },
        ),
        migrations.CreateModel(
            name='AutomatedSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autosystem_name', models.CharField(max_length=255, verbose_name='Полное название системы автоматизации')),
                ('autosystem_short_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Короткое название системы автоматизации')),
                ('system_status', models.CharField(choices=[('active', 'В эксплуатации'), ('planned', 'Планируется'), ('unsupported', 'Не поддерживается'), ('decommissioned', 'Выведена из эксплуатации')], default='active', max_length=50, verbose_name='Статус системы')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Дополнительная информация')),
                ('release_year', models.DateField(blank=True, null=True, verbose_name='Дата выпуска')),
                ('technical_specs', models.JSONField(blank=True, null=True, verbose_name='Технические характеристики')),
                ('modules', models.JSONField(blank=True, null=True, verbose_name='Модули системы')),
                ('interfaces', models.JSONField(blank=True, null=True, verbose_name='Интерфейсы системы')),
                ('creator_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('system_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='systems', to='system.automationclass', verbose_name='Класс системы')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='systems', to='system.vendorproduct', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Автоматизированная система',
                'verbose_name_plural': 'Автоматизированные системы',
            },
        ),
    ]
