# Generated by Django 6.0.5 on 2026-07-06 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_vendorproduct_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedsystem',
            name='subsystem_classes',
            field=models.ManyToManyField(blank=True, help_text='Заполняется только для составных классов (MES, MOM, АСУТП): какие классы входят в систему.', related_name='subsystem_of_systems', to='system.automationclass', verbose_name='Классы подсистем'),
        ),
        migrations.AddField(
            model_name='automationclass',
            name='includes',
            field=models.ForeignKey(blank=True, help_text='Класс, который автоматически подставляется в подсистемы (напр. у MOM здесь MES).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='included_by', to='system.automationclass', verbose_name='Включает класс'),
        ),
        migrations.AddField(
            model_name='automationclass',
            name='is_composite',
            field=models.BooleanField(default=False, help_text='Класс, который может включать подсистемы (MES, MOM, АСУТП и т.п.). Для таких систем заполняются «классы подсистем».', verbose_name='Составной класс'),
        ),
        migrations.AddField(
            model_name='automationclass',
            name='name_ru',
            field=models.CharField(blank=True, default='', help_text='Русская аббревиатура класса, если есть (напр. РСУ, ПАЗ, ТОИР).', max_length=255, verbose_name='Русская аббревиатура'),
        ),
        migrations.AlterField(
            model_name='automationclass',
            name='system_class',
            field=models.CharField(max_length=255, verbose_name='Класс системы (англ. аббревиатура)'),
        ),
    ]
