# Generated by Django 6.0.5 on 2026-06-22 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
        ('system', '0002_automatedsystem_creator_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedsystem',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_systems', to='participants.participant', verbose_name='Вендор'),
        ),
    ]
