# Generated by Django 6.0.5 on 2026-06-29 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
        ('system', '0003_automatedsystem_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedsystem',
            name='article',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='automatedsystem',
            name='autosystem_short_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Короткое название системы автоматизации'),
        ),
        migrations.AddField(
            model_name='automatedsystem',
            name='end_of_support',
            field=models.DateField(blank=True, null=True, verbose_name='Конец поддержки'),
        ),
        migrations.AddField(
            model_name='automatedsystem',
            name='interfaces',
            field=models.JSONField(blank=True, null=True, verbose_name='Интерфейсы системы'),
        ),
        migrations.AddField(
            model_name='automatedsystem',
            name='modules',
            field=models.JSONField(blank=True, null=True, verbose_name='Модули системы'),
        ),
        migrations.AddField(
            model_name='automatedsystem',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Дополнительная информация'),
        ),
        migrations.AddField(
            model_name='automatedsystem',
            name='product_type',
            field=models.CharField(blank=True, choices=[('software', 'Программное обеспечение'), ('hardware', 'Оборудование'), ('service', 'Сервис')], default='software', max_length=50, verbose_name='Тип продукта'),
        ),
        migrations.AddField(
            model_name='automatedsystem',
            name='release_year',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выпуска'),
        ),
        migrations.AddField(
            model_name='automatedsystem',
            name='system_status',
            field=models.CharField(choices=[('active', 'В эксплуатации'), ('planned', 'Планируется'), ('unsupported', 'Не поддерживается'), ('decommissioned', 'Выведена из эксплуатации')], default='active', max_length=50, verbose_name='Статус системы'),
        ),
        migrations.AddField(
            model_name='automatedsystem',
            name='technical_specs',
            field=models.JSONField(blank=True, null=True, verbose_name='Технические характеристики'),
        ),
        migrations.AddField(
            model_name='automatedsystem',
            name='version',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Версия системы'),
        ),
        migrations.AlterField(
            model_name='automatedsystem',
            name='autosystem_name',
            field=models.CharField(max_length=255, verbose_name='Полное название системы автоматизации'),
        ),
        migrations.AlterField(
            model_name='automatedsystem',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_systems', to='participants.participant', verbose_name='Поставщик системы'),
        ),
    ]
