# Generated by Django 6.0.5 on 2026-07-06 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_automatedsystem_subsystem_classes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorproduct',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='vendorproduct',
            name='end_of_support',
            field=models.DateField(blank=True, null=True, verbose_name='Конец поддержки'),
        ),
        migrations.AddField(
            model_name='vendorproduct',
            name='product_type',
            field=models.CharField(blank=True, choices=[('software', 'ПО'), ('hardware', 'Технические средства'), ('complex', 'ПАК')], default='', max_length=50, verbose_name='Тип продукта'),
        ),
        migrations.AddField(
            model_name='vendorproduct',
            name='release_year',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выпуска'),
        ),
        migrations.AddField(
            model_name='vendorproduct',
            name='system_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='system.automationclass', verbose_name='Класс системы'),
        ),
        migrations.AddField(
            model_name='vendorproduct',
            name='version',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Версия'),
        ),
    ]
