# Generated by Django 6.0.5 on 2026-07-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_vendorproduct_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorproduct',
            name='subsystem_classes',
            field=models.ManyToManyField(blank=True, help_text='Заполняется только для составных классов (MES, MOM, АСУТП): какие классы входят в продукт.', related_name='subsystem_of_products', to='system.automationclass', verbose_name='Классы подсистем'),
        ),
    ]
