# Generated by Django 6.0.5 on 2026-07-08 16:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
        ('system', '0005_vendorproduct_subsystem_classes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AutomatedSystem',
            new_name='AutomationSystem',
        ),
    ]
