# Generated by Django 6.0.5 on 2026-07-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_rename_automatedsystem_automationsystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorproduct',
            name='industries',
            field=models.JSONField(blank=True, help_text='Список отраслей (значения из категорий 1-го уровня, без связи).', null=True, verbose_name='Отрасли применения'),
        ),
        migrations.AddField(
            model_name='vendorproduct',
            name='technical_specs',
            field=models.JSONField(blank=True, help_text='Словарь «характеристика — значение».', null=True, verbose_name='Технические характеристики'),
        ),
    ]
