# Generated by Django 6.0.5 on 2026-07-12 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_alter_vendorproduct_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automationsystem',
            old_name='creator_id',
            new_name='creator',
        ),
    ]
