# Generated by Django 6.0.5 on 2026-07-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_rename_creator_id_category_creator'),
        ('system', '0009_rename_creator_id_automationsystem_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorproduct',
            name='industries',
        ),
        migrations.AddField(
            model_name='vendorproduct',
            name='industries',
            field=models.ManyToManyField(blank=True, help_text='Отрасли — категории 1-го уровня (ссылки на справочник).', related_name='industry_products', to='categories.category', verbose_name='Отрасли применения'),
        ),
    ]
