# Generated by Django 6.0.5 on 2026-07-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_remove_vendorproduct_industries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationsystem',
            name='system_status',
            field=models.CharField(choices=[('active', 'В эксплуатации'), ('planned', 'Планируется'), ('unsupported', 'Не поддерживается'), ('decommissioned', 'Не эксплуатируется')], default='active', max_length=50, verbose_name='Статус системы'),
        ),
    ]
