# Generated by Django 6.0.5 on 2026-05-21 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название характеристики')),
                ('code', models.CharField(max_length=50, verbose_name='Код характеристики')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Единица измерения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательная')),
            ],
            options={
                'verbose_name': 'Характеристика класса',
                'verbose_name_plural': 'Характеристики классов',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('region', models.CharField(max_length=100, verbose_name='Регион')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=200, verbose_name='Улица')),
                ('house', models.CharField(max_length=20, verbose_name='Дом')),
                ('fias_code', models.CharField(blank=True, max_length=36, null=True, verbose_name='Код ФИАС')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
                'indexes': [models.Index(fields=['country', 'city'], name='core_addres_country_46bfbe_idx'), models.Index(fields=['fias_code'], name='core_addres_fias_co_94b829_idx')],
            },
        ),
        migrations.CreateModel(
            name='AutomationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код уровня')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('system_classes', models.JSONField(default=list, verbose_name='Классы систем уровня')),
            ],
            options={
                'verbose_name': 'Уровень автоматизации',
                'verbose_name_plural': 'Уровни автоматизации',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['code'], name='core_automa_code_fa45b0_idx'), models.Index(fields=['order'], name='core_automa_order_e77aaf_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompanyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название группы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Группа компаний',
                'verbose_name_plural': 'Группы компаний',
                'indexes': [models.Index(fields=['name'], name='core_compan_name_161972_idx')],
            },
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('inn', models.CharField(max_length=12, unique=True, verbose_name='ИНН')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.companygroup', verbose_name='Группа компаний')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.legalentity', verbose_name='Собственник')),
            ],
            options={
                'verbose_name': 'Юридическое лицо',
                'verbose_name_plural': 'Юридические лица',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('short_name', models.CharField(blank=True, help_text='Например: Г-43-107, АВТ-6', max_length=50, verbose_name='Короткое название')),
                ('hierarchy_level', models.CharField(choices=[('LEVEL_1', 'Уровень 1 (Предприятие/НПЗ)'), ('LEVEL_2', 'Уровень 2 (Установка/Цех)'), ('LEVEL_3', 'Уровень 3 (Агрегат/Блок/Оборудование)')], max_length=20, verbose_name='Уровень иерархии')),
                ('technology', models.CharField(blank=True, max_length=100, verbose_name='Технология (АВТ, МТБЭ, каткрекинг и пр.)')),
                ('category', models.CharField(choices=[('MAIN', 'Основное производство'), ('AUX', 'Вспомогательное производство (ОЗХ)'), ('INFRA', 'Инфраструктура (АБК)'), ('PREP', 'Подготовка сырья'), ('STORAGE', 'Хранение и логистика')], max_length=20, verbose_name='Категория')),
                ('start_year', models.IntegerField(verbose_name='Год ввода в эксплуатацию')),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Мощность, тыс.тонн/год')),
                ('status', models.CharField(choices=[('ACTIVE', 'Активный'), ('PROJECT', 'В проекте'), ('RECONSTRUCTION', 'Реконструкция'), ('STOPPED', 'Остановлен')], default='ACTIVE', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.address', verbose_name='Адрес')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_objects', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.legalentity', verbose_name='Юридическое лицо')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.object', verbose_name='Родительский объект')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'ordering': ['hierarchy_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ObjectAutomationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PLANNED', 'Запланировано'), ('IN_PROGRESS', 'В реализации'), ('COMPLETED', 'Реализовано'), ('PARTIAL', 'Частично реализовано')], default='PLANNED', max_length=20)),
                ('implementation_year', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.automationlevel')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_levels', to='core.object')),
            ],
            options={
                'verbose_name': 'Уровень автоматизации объекта',
                'verbose_name_plural': 'Уровни автоматизации объектов',
            },
        ),
        migrations.CreateModel(
            name='ObjectCharacteristicValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200, verbose_name='Значение')),
                ('measurement_date', models.DateField(blank=True, null=True, verbose_name='Дата измерения')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classcharacteristic')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristic_values', to='core.object')),
            ],
            options={
                'verbose_name': 'Значение характеристики объекта',
                'verbose_name_plural': 'Значения характеристик объектов',
                'ordering': ['object', 'characteristic'],
            },
        ),
        migrations.CreateModel(
            name='ObjectClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название класса')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код класса')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_classes', to='core.objectclass', verbose_name='Родительский класс')),
            ],
            options={
                'verbose_name': 'Класс объекта',
                'verbose_name_plural': 'Классы объектов',
            },
        ),
        migrations.AddField(
            model_name='object',
            name='object_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objects_in_class', to='core.objectclass', verbose_name='Класс объекта'),
        ),
        migrations.AddField(
            model_name='classcharacteristic',
            name='object_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='core.objectclass'),
        ),
        migrations.CreateModel(
            name='ClassAutomationRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.TextField(verbose_name='Требование')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Обязательное')),
                ('regulation', models.CharField(blank=True, max_length=200, verbose_name='Норматив')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.automationlevel')),
                ('object_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_requirements', to='core.objectclass')),
            ],
            options={
                'verbose_name': 'Требование автоматизации класса',
                'verbose_name_plural': 'Требования автоматизации классов',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('inn', models.CharField(max_length=12, unique=True, verbose_name='ИНН')),
                ('participant_type', models.CharField(choices=[('VENDOR', 'Вендор (разработчик ПО/оборудования)'), ('ENGINEERING', 'Компания интегратор'), ('FULL_CYCLE', 'Вендор полного цикла'), ('SUPPLIER', 'Поставщик (продавец)')], max_length=20, verbose_name='Тип участника')),
                ('is_partner', models.BooleanField(default=False, verbose_name='Флаг партнёра')),
                ('industries', models.JSONField(default=list, verbose_name='Отрасли')),
                ('contacts', models.JSONField(default=dict, verbose_name='Контактная информация')),
                ('profile', models.TextField(blank=True, verbose_name='Профиль компании')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Дата регистрации')),
                ('website', models.URLField(blank=True, verbose_name='Сайт российского представительства')),
                ('kam_name', models.CharField(blank=True, max_length=100, verbose_name='Ответственный КАМ (ФИО)')),
                ('kam_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон КАМ')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Контактное лицо от ЦК ПА')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон контакта')),
                ('presentation_url', models.URLField(blank=True, verbose_name='Ссылка на презентацию')),
                ('financial_data', models.JSONField(default=list, help_text='[{"year": 2023, "revenue": 1500, "profit": 200, "employees": 50}, ...]', verbose_name='Финансовые показатели')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_participants', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Оценка')),
                ('date', models.DateField(verbose_name='Дата отзыва')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='Источник')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.participant', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='VendorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название продукта')),
                ('product_type', models.CharField(choices=[('SOFTWARE', 'Программное обеспечение'), ('HARDWARE', 'Аппаратное обеспечение'), ('SERVICE', 'Услуга/Сервис'), ('PLATFORM', 'Платформа'), ('SOLUTION', 'Комплексное решение'), ('CONSULTING', 'Консалтинг'), ('MAINTENANCE', 'Техническое обслуживание')], max_length=20, verbose_name='Тип продукта')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Артикул/Код')),
                ('description', models.TextField(verbose_name='Описание продукта')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='Версия')),
                ('system_types', models.JSONField(default=list, verbose_name='Типы систем')),
                ('industries', models.JSONField(default=list, verbose_name='Отрасли применения')),
                ('technical_specs', models.JSONField(default=dict, verbose_name='Технические характеристики')),
                ('release_year', models.IntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('end_of_support', models.DateField(blank=True, null=True, verbose_name='Конец поддержки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный продукт')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_products', to='core.participant', verbose_name='Вендор')),
            ],
            options={
                'verbose_name': 'Вендорский продукт',
                'verbose_name_plural': 'Вендорские продукты',
                'ordering': ['vendor__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TCOAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capex', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='CAPEX (млн руб)')),
                ('opex_per_year', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='OPEX в год (млн руб)')),
                ('period_years', models.IntegerField(default=5, verbose_name='Период анализа (лет)')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Ставка дисконтирования %')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tco', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tco_analyses', to='core.participant', verbose_name='Участник')),
                ('vendor_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tco_analyses', to='core.vendorproduct', verbose_name='Вендорский продукт')),
            ],
            options={
                'verbose_name': 'TCO анализ',
                'verbose_name_plural': 'TCO анализы',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('year', models.IntegerField(verbose_name='Год реализации')),
                ('successful', models.BooleanField(default=True, verbose_name='Успешный пуск')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.object', verbose_name='Объект внедрения')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.participant', verbose_name='Участник')),
                ('vendor_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.vendorproduct', verbose_name='Вендорский продукт')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название сертификата')),
                ('certificate_type', models.CharField(choices=[('ISO', 'Сертификат ISO'), ('AUTHORIZED', 'Авторизация вендора'), ('SPECIALIST', 'Сертифицированный специалист'), ('OTHER', 'Другое')], max_length=20, verbose_name='Тип сертификата')),
                ('issued_by', models.CharField(max_length=200, verbose_name='Кем выдан')),
                ('issued_date', models.DateField(verbose_name='Дата выдачи')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Срок действия')),
                ('file', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Файл сертификата')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_certificates', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core.participant', verbose_name='Участник')),
                ('vendor_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='core.vendorproduct', verbose_name='Вендорский продукт')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='AutomatedSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название системы')),
                ('system_class', models.CharField(blank=True, choices=[('DCS', 'DCS (Распределённая система управления)'), ('HMI', 'HMI (Человеко-машинный интерфейс)'), ('ESD', 'ESD (Аварийная система отключения)'), ('APC', 'APC (Расширенное управление процессом)'), ('FGS', 'FGS (Система контроля пламени и газа)'), ('MES', 'MES (Система управления производством)'), ('MES+', 'MES+ (Расширенный MES)'), ('MOM', 'MOM (Manufacturing Operations Management)'), ('APS', 'APS (Advanced Planning and Scheduling)'), ('OEE', 'OEE (Overall Equipment Effectiveness)'), ('LIMS', 'LIMS (Laboratory Information Management System)'), ('WMS', 'WMS (Warehouse Management System)'), ('CMMS', 'CMMS (Computerized Maintenance Management System)'), ('DT', 'DT (Digital Twin)'), ('DRTO', 'DRTO (Dynamic Real-Time Optimization)'), ('ERP', 'ERP (Enterprise Resource Planning)'), ('PLM', 'PLM (Product Lifecycle Management)'), ('CRM', 'CRM (Customer Relationship Management)'), ('HRM', 'HRM (Human Resource Management)'), ('PDES', 'PDES (Product Data Exchange Specification)'), ('SCADA', 'SCADA (Supervisory Control And Data Acquisition)'), ('PLC', 'PLC (Programmable Logic Controller)'), ('SENSORS', 'Датчики и сенсоры'), ('FIELD_DEVICES', 'Полевые устройства')], max_length=50, verbose_name='Класс системы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='Версия')),
                ('modules', models.JSONField(default=list, verbose_name='Модули системы')),
                ('interfaces', models.JSONField(default=list, verbose_name='Интерфейсы')),
                ('status', models.CharField(choices=[('ACTIVE', 'Активна'), ('INACTIVE', 'Неактивна'), ('MAINTENANCE', 'На обслуживании'), ('UPGRADE', 'На модернизации')], default='ACTIVE', max_length=20, verbose_name='Статус')),
                ('installation_date', models.DateField(blank=True, null=True, verbose_name='Дата установки')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_systems', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.automationlevel', verbose_name='Уровень автоматизации')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automated_systems', to='core.object')),
                ('implementer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='automated_systems_implementer', to='core.participant', verbose_name='Внедряющая компания')),
                ('integrator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automated_systems_integrator', to='core.participant', verbose_name='Интегратор (Инжиниринговая компания)')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='automated_systems_vendor', to='core.participant', verbose_name='Вендор')),
                ('vendor_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automated_systems', to='core.vendorproduct', verbose_name='Вендорский продукт')),
            ],
            options={
                'verbose_name': 'Автоматизированная система',
                'verbose_name_plural': 'Автоматизированные системы',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('action', models.CharField(choices=[('CREATE', 'Создание'), ('UPDATE', 'Изменение'), ('DELETE', 'Удаление'), ('RESTORE', 'Восстановление')], max_length=20, verbose_name='Действие')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID объекта')),
                ('object_repr', models.CharField(max_length=255, verbose_name='Представление объекта')),
                ('changes', models.JSONField(default=dict, verbose_name='Изменения')),
                ('snapshot', models.JSONField(default=dict, verbose_name='Снимок состояния')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип модели')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Журнал аудита',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_auditl_content_fec0c4_idx'), models.Index(fields=['user', '-timestamp'], name='core_auditl_user_id_2a1528_idx'), models.Index(fields=['action', 'timestamp'], name='core_auditl_action_096de0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='legalentity',
            index=models.Index(fields=['name'], name='core_legale_name_43ceb6_idx'),
        ),
        migrations.AddIndex(
            model_name='legalentity',
            index=models.Index(fields=['inn'], name='core_legale_inn_3c0700_idx'),
        ),
        migrations.AddIndex(
            model_name='legalentity',
            index=models.Index(fields=['group', 'owner'], name='core_legale_group_i_f86a93_idx'),
        ),
        migrations.AddIndex(
            model_name='objectautomationlevel',
            index=models.Index(fields=['object', 'status'], name='core_object_object__098d8a_idx'),
        ),
        migrations.AddIndex(
            model_name='objectautomationlevel',
            index=models.Index(fields=['level', 'status'], name='core_object_level_i_6a147f_idx'),
        ),
        migrations.AddIndex(
            model_name='objectautomationlevel',
            index=models.Index(fields=['implementation_year'], name='core_object_impleme_c9ed67_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='objectautomationlevel',
            unique_together={('object', 'level')},
        ),
        migrations.AddIndex(
            model_name='objectcharacteristicvalue',
            index=models.Index(fields=['object', 'characteristic'], name='core_object_object__7bf30f_idx'),
        ),
        migrations.AddIndex(
            model_name='objectcharacteristicvalue',
            index=models.Index(fields=['measurement_date'], name='core_object_measure_1586f7_idx'),
        ),
        migrations.AddIndex(
            model_name='objectcharacteristicvalue',
            index=models.Index(fields=['characteristic', 'value'], name='core_object_charact_f0f9a0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='objectcharacteristicvalue',
            unique_together={('object', 'characteristic')},
        ),
        migrations.AddIndex(
            model_name='objectclass',
            index=models.Index(fields=['code'], name='core_object_code_d3fe2b_idx'),
        ),
        migrations.AddIndex(
            model_name='objectclass',
            index=models.Index(fields=['name'], name='core_object_name_466b30_idx'),
        ),
        migrations.AddIndex(
            model_name='objectclass',
            index=models.Index(fields=['parent'], name='core_object_parent__08a82f_idx'),
        ),
        migrations.AddIndex(
            model_name='object',
            index=models.Index(fields=['hierarchy_level'], name='core_object_hierarc_ec2adc_idx'),
        ),
        migrations.AddIndex(
            model_name='object',
            index=models.Index(fields=['status'], name='core_object_status_9d532e_idx'),
        ),
        migrations.AddIndex(
            model_name='object',
            index=models.Index(fields=['object_class'], name='core_object_object__04ad7e_idx'),
        ),
        migrations.AddIndex(
            model_name='object',
            index=models.Index(fields=['short_name'], name='core_object_short_n_3a88e9_idx'),
        ),
        migrations.AddIndex(
            model_name='object',
            index=models.Index(fields=['hierarchy_level', 'status'], name='obj_level_status_idx'),
        ),
        migrations.AddIndex(
            model_name='object',
            index=models.Index(fields=['parent_id', 'hierarchy_level'], name='obj_parent_level_idx'),
        ),
        migrations.AddIndex(
            model_name='object',
            index=models.Index(fields=['legal_entity', 'hierarchy_level'], name='obj_legal_level_idx'),
        ),
        migrations.AddIndex(
            model_name='object',
            index=models.Index(fields=['object_class', 'start_year'], name='obj_class_year_idx'),
        ),
        migrations.AddIndex(
            model_name='object',
            index=models.Index(fields=['technology'], name='obj_technology_idx'),
        ),
        migrations.AddIndex(
            model_name='classcharacteristic',
            index=models.Index(fields=['object_class', 'is_required'], name='core_classc_object__5ff8be_idx'),
        ),
        migrations.AddIndex(
            model_name='classcharacteristic',
            index=models.Index(fields=['code'], name='core_classc_code_457980_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classcharacteristic',
            unique_together={('object_class', 'code')},
        ),
        migrations.AddIndex(
            model_name='classautomationrequirement',
            index=models.Index(fields=['object_class', 'is_mandatory'], name='core_classa_object__b758b7_idx'),
        ),
        migrations.AddIndex(
            model_name='classautomationrequirement',
            index=models.Index(fields=['level', 'is_mandatory'], name='core_classa_level_i_b83ce2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classautomationrequirement',
            unique_together={('object_class', 'level')},
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['name'], name='core_partic_name_9334b3_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['inn'], name='core_partic_inn_48f50e_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['participant_type', 'is_partner'], name='core_partic_partici_220eca_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['registration_date'], name='core_partic_registr_95175d_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['participant', 'rating'], name='review_participant_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorproduct',
            index=models.Index(fields=['name'], name='core_vendor_name_56522a_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorproduct',
            index=models.Index(fields=['code'], name='core_vendor_code_1f6e76_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorproduct',
            index=models.Index(fields=['vendor', 'product_type'], name='core_vendor_vendor__29a1a3_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorproduct',
            index=models.Index(fields=['release_year'], name='core_vendor_release_54c698_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorproduct',
            index=models.Index(fields=['is_active'], name='core_vendor_is_acti_6929d4_idx'),
        ),
        migrations.AddIndex(
            model_name='tcoanalysis',
            index=models.Index(fields=['participant', 'vendor_product'], name='tco_participant_product_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['participant', 'year'], name='project_participant_year_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['object', 'year'], name='project_object_year_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['participant', 'certificate_type'], name='cert_participant_type_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['expiry_date'], name='cert_expiry_date_idx'),
        ),
        migrations.AddIndex(
            model_name='automatedsystem',
            index=models.Index(fields=['name'], name='core_automa_name_2a4e41_idx'),
        ),
        migrations.AddIndex(
            model_name='automatedsystem',
            index=models.Index(fields=['system_class'], name='core_automa_system__d367cd_idx'),
        ),
        migrations.AddIndex(
            model_name='automatedsystem',
            index=models.Index(fields=['status'], name='core_automa_status_cc49c7_idx'),
        ),
        migrations.AddIndex(
            model_name='automatedsystem',
            index=models.Index(fields=['installation_date'], name='core_automa_install_487dc2_idx'),
        ),
        migrations.AddIndex(
            model_name='automatedsystem',
            index=models.Index(fields=['object', 'system_class'], name='core_automa_object__e26049_idx'),
        ),
        migrations.AddIndex(
            model_name='automatedsystem',
            index=models.Index(fields=['vendor', 'status'], name='core_automa_vendor__e92852_idx'),
        ),
        migrations.AddIndex(
            model_name='automatedsystem',
            index=models.Index(fields=['level', 'status'], name='core_automa_level_i_02aa02_idx'),
        ),
        migrations.AddIndex(
            model_name='automatedsystem',
            index=models.Index(fields=['object_id', 'vendor_id'], name='sys_object_vendor_idx'),
        ),
        migrations.AddIndex(
            model_name='automatedsystem',
            index=models.Index(fields=['object_id', 'integrator_id'], name='sys_object_integrator_idx'),
        ),
        migrations.AddIndex(
            model_name='automatedsystem',
            index=models.Index(fields=['vendor_product', 'status'], name='sys_product_status_idx'),
        ),
    ]
