# Generated by Django 6.0.6 on 2026-06-07 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Уровень 1'), (2, 'Уровень 2'), (3, 'Уровень 3')], verbose_name='уровень')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'db_table': 'category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Уровень 1'), (2, 'Уровень 2'), (3, 'Уровень 3')], db_index=True, verbose_name='уровень')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_objects', to='core.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'объект',
                'verbose_name_plural': 'объекты',
                'db_table': 'object',
                'ordering': ['name'],
            },
        ),
    ]
