# Generated by Django 6.0.5 on 2026-07-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=255, verbose_name='Название участника рынка')),
                ('inn', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='ИНН')),
                ('contacts', models.JSONField(blank=True, null=True, verbose_name='Контактная информация')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Дата регистрации')),
                ('financial_data', models.JSONField(blank=True, null=True, verbose_name='Финансовые показатели')),
                ('entity_type', models.CharField(blank=True, choices=[('vendor', 'Вендор'), ('system_integrator', 'Системный интегратор'), ('engineering_company', 'Инжиниринговая компания'), ('full_cycle_vendor', 'Вендор полного цикла'), ('supplier', 'Поставщик')], default='', max_length=50, verbose_name='Тип участника')),
                ('is_partner', models.BooleanField(default=False, verbose_name='Является ли партнёром')),
                ('website', models.CharField(blank=True, default='', max_length=255, verbose_name='Ссылка на сайт')),
                ('kam_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Имя КАМ (Key Account Manager)')),
                ('kam_phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Телефон КАМ')),
                ('contact_person', models.CharField(blank=True, default='', max_length=255, verbose_name='Контакт от ЦК ПА')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Телефон от ЦК ПА')),
                ('presentation_url', models.CharField(blank=True, default='', max_length=255, verbose_name='Ссылка на презентацию')),
                ('profile', models.TextField(blank=True, default='', verbose_name='Профиль компании')),
                ('industries', models.JSONField(blank=True, null=True, verbose_name='Отрасли применения')),
            ],
            options={
                'verbose_name': 'Участник рынка',
                'verbose_name_plural': 'Участники рынка',
                'ordering': ['entity_name'],
            },
        ),
    ]
