# Generated by Django 6.0.5 on 2026-07-08 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
        ('objects', '0001_initial'),
        ('system', '0007_vendorproduct_industries_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineeringCompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, default='', help_text='Регион деятельности. Подсказки — регионы существующих объектов.', max_length=255, verbose_name='Локация (регион)')),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engineering_profile', to='entities.entity', verbose_name='Участник')),
                ('product_competencies', models.ManyToManyField(blank=True, related_name='competent_engineering_companies', to='system.vendorproduct', verbose_name='Узкая компетенция по продуктам')),
                ('resident_object', models.ForeignKey(blank=True, help_text='Объект, на котором компания уже закрепилась и работает.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_engineering_companies', to='objects.object', verbose_name='Вхожий объект')),
            ],
            options={
                'verbose_name': 'Профиль инжиниринговой компании',
                'verbose_name_plural': 'Профили инжиниринговых компаний',
            },
        ),
        migrations.CreateModel(
            name='FunctionCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(help_text='Значение из категорий 1-го уровня (без жёсткой связи).', max_length=255, verbose_name='Индустрия')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='function_competencies', to='entities.engineeringcompanyprofile', verbose_name='Профиль инжиниринговой компании')),
                ('system_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='function_competencies', to='system.automationclass', verbose_name='Класс систем')),
            ],
            options={
                'verbose_name': 'Компетенция по функции',
                'verbose_name_plural': 'Компетенции по функции',
                'ordering': ['system_class__level', 'system_class__system_class', 'industry'],
            },
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to='entities.entity', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Профиль вендора',
                'verbose_name_plural': 'Профили вендоров',
            },
        ),
    ]
