# Generated by Django 6.0.5 on 2026-07-12 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_engineeringcompanyprofile_functioncompetency_and_more'),
        ('system', '0008_alter_vendorproduct_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_profile', to='entities.entity', verbose_name='Участник')),
                ('products', models.ManyToManyField(blank=True, related_name='suppliers', to='system.vendorproduct', verbose_name='Поставляемые продукты')),
            ],
            options={
                'verbose_name': 'Профиль поставщика',
                'verbose_name_plural': 'Профили поставщиков',
            },
        ),
    ]
