# Generated by Django 6.0.5 on 2026-07-12 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_supplierprofile'),
        ('owners', '0002_ownerentity_is_root'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemIntegratorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system_integrator_profile', to='entities.entity', verbose_name='Участник')),
                ('managing_owner', models.ForeignKey(blank=True, help_text='Компания из OwnerEntity, если это внутренний интегратор.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_integrators', to='owners.ownerentity', verbose_name='Управляющая компания')),
                ('vendor_partners', models.ManyToManyField(blank=True, related_name='partner_integrators', to='entities.vendorprofile', verbose_name='Вендоры-партнёры')),
            ],
            options={
                'verbose_name': 'Профиль системного интегратора',
                'verbose_name_plural': 'Профили системных интеграторов',
            },
        ),
    ]
