# Generated by Django 6.0.5 on 2026-07-12 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_backfill_full_cycle_vendor_profiles'),
        ('objects', '0003_alter_object_options_and_more'),
        ('system', '0008_alter_vendorproduct_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullCycleVendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, default='', help_text='Регион деятельности. Подсказки — регионы существующих объектов.', max_length=255, verbose_name='Локация (регион)')),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='full_cycle_profile', to='entities.entity', verbose_name='Участник')),
                ('products', models.ManyToManyField(blank=True, related_name='full_cycle_competent_vendors', to='system.vendorproduct', verbose_name='Узкая компетенция по продуктам')),
                ('resident_object', models.ForeignKey(blank=True, help_text='Объект, на котором компания уже закрепилась и работает.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_full_cycle_vendors', to='objects.object', verbose_name='Вхожий объект')),
            ],
            options={
                'verbose_name': 'Профиль вендора полного цикла',
                'verbose_name_plural': 'Профили вендоров полного цикла',
            },
        ),
        migrations.CreateModel(
            name='FullCycleFunctionCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(help_text='Значение из категорий 1-го уровня (без жёсткой связи).', max_length=255, verbose_name='Индустрия')),
                ('system_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_cycle_function_competencies', to='system.automationclass', verbose_name='Класс систем')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='function_competencies', to='entities.fullcyclevendorprofile', verbose_name='Профиль вендора полного цикла')),
            ],
            options={
                'verbose_name': 'Компетенция по функции (полный цикл)',
                'verbose_name_plural': 'Компетенции по функции (полный цикл)',
                'ordering': ['system_class__level', 'system_class__system_class', 'industry'],
            },
        ),
    ]
