# Generated by Django 6.0.5 on 2026-07-18 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_rename_creator_id_category_creator'),
        ('entities', '0006_add_full_cycle_vendor_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fullcyclefunctioncompetency',
            options={'ordering': ['system_class__level', 'system_class__system_class', 'industry__category_name'], 'verbose_name': 'Компетенция по функции (полный цикл)', 'verbose_name_plural': 'Компетенции по функции (полный цикл)'},
        ),
        migrations.AlterModelOptions(
            name='functioncompetency',
            options={'ordering': ['system_class__level', 'system_class__system_class', 'industry__category_name'], 'verbose_name': 'Компетенция по функции', 'verbose_name_plural': 'Компетенции по функции'},
        ),
        migrations.RemoveField(
            model_name='entity',
            name='industries',
        ),
        migrations.AlterField(
            model_name='fullcyclefunctioncompetency',
            name='industry',
            field=models.ForeignKey(help_text='Индустрия — категория 1-го уровня (ссылка на справочник).', on_delete=django.db.models.deletion.CASCADE, related_name='full_cycle_function_competencies', to='categories.category', verbose_name='Индустрия'),
        ),
        migrations.AlterField(
            model_name='functioncompetency',
            name='industry',
            field=models.ForeignKey(help_text='Индустрия — категория 1-го уровня (ссылка на справочник).', on_delete=django.db.models.deletion.CASCADE, related_name='function_competencies', to='categories.category', verbose_name='Индустрия'),
        ),
        migrations.AddField(
            model_name='entity',
            name='industries',
            field=models.ManyToManyField(blank=True, help_text='Отрасли — категории 1-го уровня (ссылки на справочник).', related_name='industry_entities', to='categories.category', verbose_name='Отрасли применения'),
        ),
    ]
