# Generated by Django 6.0.5 on 2026-07-18 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0007_alter_fullcyclefunctioncompetency_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='industries',
        ),
    ]
