# Generated by Django 6.0.5 on 2026-07-18 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_rename_creator_id_category_creator'),
        ('entities', '0008_remove_entity_industries'),
        ('system', '0010_remove_vendorproduct_industries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullcyclefunctioncompetency',
            name='industry',
            field=models.ForeignKey(blank=True, help_text='Индустрия — категория 1-го уровня. Пусто — все отрасли.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='full_cycle_function_competencies', to='categories.category', verbose_name='Индустрия'),
        ),
        migrations.AlterField(
            model_name='fullcyclefunctioncompetency',
            name='system_class',
            field=models.ForeignKey(blank=True, help_text='Пусто — все классы (в указанной отрасли).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='full_cycle_function_competencies', to='system.automationclass', verbose_name='Класс систем'),
        ),
        migrations.CreateModel(
            name='EngineeringCompanyFunctionCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.ForeignKey(blank=True, help_text='Индустрия — категория 1-го уровня. Пусто — все отрасли.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eng_function_competencies', to='categories.category', verbose_name='Индустрия')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='function_competencies', to='entities.engineeringcompanyprofile', verbose_name='Профиль инжиниринговой компании')),
                ('system_class', models.ForeignKey(blank=True, help_text='Пусто — все классы (в указанной отрасли).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eng_function_competencies', to='system.automationclass', verbose_name='Класс систем')),
            ],
            options={
                'verbose_name': 'Компетенция инж. компании по функции',
                'verbose_name_plural': 'Компетенции инж. компании по функции',
                'ordering': ['system_class__level', 'system_class__system_class', 'industry__category_name'],
            },
        ),
        migrations.CreateModel(
            name='SystemIntegratorFunctionCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.ForeignKey(blank=True, help_text='Индустрия — категория 1-го уровня. Пусто — исключение во всех отраслях.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integrator_excluded_competencies', to='categories.category', verbose_name='Индустрия (исключение)')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='function_competencies', to='entities.systemintegratorprofile', verbose_name='Профиль системного интегратора')),
                ('system_class', models.ForeignKey(blank=True, help_text='Пусто — исключение по всем классам (в указанной отрасли).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integrator_excluded_competencies', to='system.automationclass', verbose_name='Класс систем (исключение)')),
            ],
            options={
                'verbose_name': 'Исключение компетенции интегратора',
                'verbose_name_plural': 'Исключения компетенций интегратора',
                'ordering': ['system_class__level', 'system_class__system_class', 'industry__category_name'],
            },
        ),
        migrations.DeleteModel(
            name='FunctionCompetency',
        ),
    ]
