# Generated by Django 6.0.5 on 2026-07-23 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0009_alter_fullcyclefunctioncompetency_industry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fullcyclevendorprofile',
            name='products',
        ),
    ]
