# Generated by Django 6.0.5 on 2026-06-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=255, verbose_name='Название участника рынка')),
            ],
            options={
                'verbose_name': 'Участник рынка',
                'verbose_name_plural': 'Участники рынка',
                'ordering': ['participant_name'],
            },
        ),
    ]
