# Generated by Django 6.0.5 on 2026-05-29 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('inn', models.CharField(max_length=12, unique=True, verbose_name='ИНН')),
                ('participant_type', models.CharField(choices=[('VENDOR', 'Вендор (разработчик ПО/оборудования)'), ('ENGINEERING', 'Компания интегратор'), ('FULL_CYCLE', 'Вендор полного цикла'), ('SUPPLIER', 'Поставщик (продавец)')], max_length=20, verbose_name='Тип участника')),
                ('is_partner', models.BooleanField(default=False, verbose_name='Флаг партнёра')),
                ('industries', models.JSONField(default=list, verbose_name='Отрасли')),
                ('contacts', models.JSONField(default=dict, verbose_name='Контактная информация')),
                ('profile', models.TextField(blank=True, verbose_name='Профиль компании')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Дата регистрации')),
                ('website', models.URLField(blank=True, verbose_name='Сайт российского представительства')),
                ('kam_name', models.CharField(blank=True, max_length=100, verbose_name='Ответственный КАМ (ФИО)')),
                ('kam_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон КАМ')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Контактное лицо от ЦК ПА')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон контакта')),
                ('presentation_url', models.URLField(blank=True, verbose_name='Ссылка на презентацию')),
                ('financial_data', models.JSONField(default=list, help_text='[{"year": 2023, "revenue": 1500, "profit": 200, "employees": 50}, ...]', verbose_name='Финансовые показатели')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_participants', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Оценка')),
                ('date', models.DateField(verbose_name='Дата отзыва')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='Источник')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='participants.participant', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='VendorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название продукта')),
                ('product_type', models.CharField(choices=[('SOFTWARE', 'Программное обеспечение'), ('HARDWARE', 'Аппаратное обеспечение'), ('SERVICE', 'Услуга/Сервис'), ('PLATFORM', 'Платформа'), ('SOLUTION', 'Комплексное решение'), ('CONSULTING', 'Консалтинг'), ('MAINTENANCE', 'Техническое обслуживание')], max_length=20, verbose_name='Тип продукта')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Артикул/Код')),
                ('description', models.TextField(verbose_name='Описание продукта')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='Версия')),
                ('system_types', models.JSONField(default=list, verbose_name='Типы систем')),
                ('industries', models.JSONField(default=list, verbose_name='Отрасли применения')),
                ('technical_specs', models.JSONField(default=dict, verbose_name='Технические характеристики')),
                ('release_year', models.IntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('end_of_support', models.DateField(blank=True, null=True, verbose_name='Конец поддержки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный продукт')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_products', to='participants.participant', verbose_name='Вендор')),
            ],
            options={
                'verbose_name': 'Вендорский продукт',
                'verbose_name_plural': 'Вендорские продукты',
                'ordering': ['vendor__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TCOAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capex', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='CAPEX (млн руб)')),
                ('opex_per_year', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='OPEX в год (млн руб)')),
                ('period_years', models.IntegerField(default=5, verbose_name='Период анализа (лет)')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Ставка дисконтирования %')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tco', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tco_analyses', to='participants.participant', verbose_name='Участник')),
                ('vendor_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tco_analyses', to='participants.vendorproduct', verbose_name='Вендорский продукт')),
            ],
            options={
                'verbose_name': 'TCO анализ',
                'verbose_name_plural': 'TCO анализы',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('year', models.IntegerField(verbose_name='Год реализации')),
                ('successful', models.BooleanField(default=True, verbose_name='Успешный пуск')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='objects.object', verbose_name='Объект внедрения')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='participants.participant', verbose_name='Участник')),
                ('vendor_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='participants.vendorproduct', verbose_name='Вендорский продукт')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название сертификата')),
                ('certificate_type', models.CharField(choices=[('ISO', 'Сертификат ISO'), ('AUTHORIZED', 'Авторизация вендора'), ('SPECIALIST', 'Сертифицированный специалист'), ('OTHER', 'Другое')], max_length=20, verbose_name='Тип сертификата')),
                ('issued_by', models.CharField(max_length=200, verbose_name='Кем выдан')),
                ('issued_date', models.DateField(verbose_name='Дата выдачи')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Срок действия')),
                ('file', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Файл сертификата')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_certificates', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='participants.participant', verbose_name='Участник')),
                ('vendor_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='participants.vendorproduct', verbose_name='Вендорский продукт')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['name'], name='participant_name_7b66fa_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['inn'], name='participant_inn_c9df32_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['participant_type', 'is_partner'], name='participant_partici_bbcce2_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['registration_date'], name='participant_registr_817670_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['participant', 'rating'], name='review_participant_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorproduct',
            index=models.Index(fields=['name'], name='participant_name_597051_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorproduct',
            index=models.Index(fields=['code'], name='participant_code_696b46_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorproduct',
            index=models.Index(fields=['vendor', 'product_type'], name='participant_vendor__522a95_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorproduct',
            index=models.Index(fields=['release_year'], name='participant_release_bc66c3_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorproduct',
            index=models.Index(fields=['is_active'], name='participant_is_acti_621983_idx'),
        ),
        migrations.AddIndex(
            model_name='tcoanalysis',
            index=models.Index(fields=['participant', 'vendor_product'], name='tco_participant_product_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['participant', 'year'], name='project_participant_year_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['object', 'year'], name='project_object_year_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['participant', 'certificate_type'], name='cert_participant_type_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['expiry_date'], name='cert_expiry_date_idx'),
        ),
    ]
