# Generated by Django 6.0.5 on 2026-05-29 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код уровня')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('system_classes', models.JSONField(default=list, verbose_name='Классы систем уровня')),
            ],
            options={
                'verbose_name': 'Уровень автоматизации',
                'verbose_name_plural': 'Уровни автоматизации',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ObjectAutomationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PLANNED', 'Запланировано'), ('IN_PROGRESS', 'В реализации'), ('COMPLETED', 'Реализовано'), ('PARTIAL', 'Частично реализовано')], default='PLANNED', max_length=20)),
                ('implementation_year', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Уровень автоматизации объекта',
                'verbose_name_plural': 'Уровни автоматизации объектов',
            },
        ),
        migrations.CreateModel(
            name='AutomatedSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название системы')),
                ('system_class', models.CharField(blank=True, choices=[('DCS', 'DCS (Распределённая система управления)'), ('HMI', 'HMI (Человеко-машинный интерфейс)'), ('ESD', 'ESD (Аварийная система отключения)'), ('APC', 'APC (Расширенное управление процессом)'), ('FGS', 'FGS (Система контроля пламени и газа)'), ('MES', 'MES (Система управления производством)'), ('MES+', 'MES+ (Расширенный MES)'), ('MOM', 'MOM (Manufacturing Operations Management)'), ('APS', 'APS (Advanced Planning and Scheduling)'), ('OEE', 'OEE (Overall Equipment Effectiveness)'), ('LIMS', 'LIMS (Laboratory Information Management System)'), ('WMS', 'WMS (Warehouse Management System)'), ('CMMS', 'CMMS (Computerized Maintenance Management System)'), ('DT', 'DT (Digital Twin)'), ('DRTO', 'DRTO (Dynamic Real-Time Optimization)'), ('ERP', 'ERP (Enterprise Resource Planning)'), ('PLM', 'PLM (Product Lifecycle Management)'), ('CRM', 'CRM (Customer Relationship Management)'), ('HRM', 'HRM (Human Resource Management)'), ('PDES', 'PDES (Product Data Exchange Specification)'), ('SCADA', 'SCADA (Supervisory Control And Data Acquisition)'), ('PLC', 'PLC (Programmable Logic Controller)'), ('SENSORS', 'Датчики и сенсоры'), ('FIELD_DEVICES', 'Полевые устройства')], max_length=50, verbose_name='Класс системы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='Версия')),
                ('modules', models.JSONField(default=list, verbose_name='Модули системы')),
                ('interfaces', models.JSONField(default=list, verbose_name='Интерфейсы')),
                ('status', models.CharField(choices=[('ACTIVE', 'Активна'), ('INACTIVE', 'Неактивна'), ('MAINTENANCE', 'На обслуживании'), ('UPGRADE', 'На модернизации')], default='ACTIVE', max_length=20, verbose_name='Статус')),
                ('installation_date', models.DateField(blank=True, null=True, verbose_name='Дата установки')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_systems', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Автоматизированная система',
                'verbose_name_plural': 'Автоматизированные системы',
            },
        ),
    ]
