# Generated by Django 6.0.5 on 2026-05-29 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automation', '0001_initial'),
        ('objects', '0001_initial'),
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedsystem',
            name='implementer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='automated_systems_implementer', to='participants.participant', verbose_name='Внедряющая компания'),
        ),
        migrations.AddField(
            model_name='automatedsystem',
            name='integrator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automated_systems_integrator', to='participants.participant', verbose_name='Интегратор (Инжиниринговая компания)'),
        ),
        migrations.AddField(
            model_name='automatedsystem',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automated_systems', to='objects.object'),
        ),
        migrations.AddField(
            model_name='automatedsystem',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='automated_systems_vendor', to='participants.participant', verbose_name='Вендор'),
        ),
        migrations.AddField(
            model_name='automatedsystem',
            name='vendor_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automated_systems', to='participants.vendorproduct', verbose_name='Вендорский продукт'),
        ),
        migrations.AddIndex(
            model_name='automationlevel',
            index=models.Index(fields=['code'], name='automation__code_4df492_idx'),
        ),
        migrations.AddIndex(
            model_name='automationlevel',
            index=models.Index(fields=['order'], name='automation__order_e42f3b_idx'),
        ),
        migrations.AddField(
            model_name='automatedsystem',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='automation.automationlevel', verbose_name='Уровень автоматизации'),
        ),
        migrations.AddField(
            model_name='objectautomationlevel',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.automationlevel'),
        ),
        migrations.AddField(
            model_name='objectautomationlevel',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_levels', to='objects.object'),
        ),
        migrations.AddIndex(
            model_name='automatedsystem',
            index=models.Index(fields=['name'], name='automation__name_e47d3c_idx'),
        ),
        migrations.AddIndex(
            model_name='automatedsystem',
            index=models.Index(fields=['system_class'], name='automation__system__8b6857_idx'),
        ),
        migrations.AddIndex(
            model_name='automatedsystem',
            index=models.Index(fields=['status'], name='automation__status_5c13e0_idx'),
        ),
        migrations.AddIndex(
            model_name='automatedsystem',
            index=models.Index(fields=['installation_date'], name='automation__install_6fc67a_idx'),
        ),
        migrations.AddIndex(
            model_name='automatedsystem',
            index=models.Index(fields=['object', 'system_class'], name='automation__object__dd0d00_idx'),
        ),
        migrations.AddIndex(
            model_name='automatedsystem',
            index=models.Index(fields=['vendor', 'status'], name='automation__vendor__8443f9_idx'),
        ),
        migrations.AddIndex(
            model_name='automatedsystem',
            index=models.Index(fields=['level', 'status'], name='automation__level_i_bb0408_idx'),
        ),
        migrations.AddIndex(
            model_name='automatedsystem',
            index=models.Index(fields=['object_id', 'vendor_id'], name='sys_object_vendor_idx'),
        ),
        migrations.AddIndex(
            model_name='automatedsystem',
            index=models.Index(fields=['object_id', 'integrator_id'], name='sys_object_integrator_idx'),
        ),
        migrations.AddIndex(
            model_name='automatedsystem',
            index=models.Index(fields=['vendor_product', 'status'], name='sys_product_status_idx'),
        ),
        migrations.AddIndex(
            model_name='objectautomationlevel',
            index=models.Index(fields=['object', 'status'], name='automation__object__88ef43_idx'),
        ),
        migrations.AddIndex(
            model_name='objectautomationlevel',
            index=models.Index(fields=['level', 'status'], name='automation__level_i_0dd207_idx'),
        ),
        migrations.AddIndex(
            model_name='objectautomationlevel',
            index=models.Index(fields=['implementation_year'], name='automation__impleme_8184cb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='objectautomationlevel',
            unique_together={('object', 'level')},
        ),
    ]
