# Generated by Django 6.0.5 on 2026-07-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_ownerentity_is_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerentity',
            name='inn',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='ИНН'),
        ),
    ]
