# Generated by Django 6.0.5 on 2026-05-29 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automation', '0001_initial'),
        ('registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название класса')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код класса')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_classes', to='objects.objectclass', verbose_name='Родительский класс')),
            ],
            options={
                'verbose_name': 'Класс объекта',
                'verbose_name_plural': 'Классы объектов',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('short_name', models.CharField(blank=True, help_text='Например: Г-43-107, АВТ-6', max_length=50, verbose_name='Короткое название')),
                ('hierarchy_level', models.CharField(choices=[('LEVEL_1', 'Уровень 1 (Предприятие/НПЗ)'), ('LEVEL_2', 'Уровень 2 (Установка/Цех)'), ('LEVEL_3', 'Уровень 3 (Агрегат/Блок/Оборудование)')], max_length=20, verbose_name='Уровень иерархии')),
                ('technology', models.CharField(blank=True, max_length=100, verbose_name='Технология (АВТ, МТБЭ, каткрекинг и пр.)')),
                ('category', models.CharField(choices=[('MAIN', 'Основное производство'), ('AUX', 'Вспомогательное производство (ОЗХ)'), ('INFRA', 'Инфраструктура (АБК)'), ('PREP', 'Подготовка сырья'), ('STORAGE', 'Хранение и логистика')], max_length=20, verbose_name='Категория')),
                ('start_year', models.IntegerField(verbose_name='Год ввода в эксплуатацию')),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Мощность, тыс.тонн/год')),
                ('status', models.CharField(choices=[('ACTIVE', 'Активный'), ('PROJECT', 'В проекте'), ('RECONSTRUCTION', 'Реконструкция'), ('STOPPED', 'Остановлен')], default='ACTIVE', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registry.address', verbose_name='Адрес')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_objects', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registry.legalentity', verbose_name='Юридическое лицо')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='objects.object', verbose_name='Родительский объект')),
                ('object_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objects_in_class', to='objects.objectclass', verbose_name='Класс объекта')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'ordering': ['hierarchy_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClassCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название характеристики')),
                ('code', models.CharField(max_length=50, verbose_name='Код характеристики')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Единица измерения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательная')),
                ('object_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='objects.objectclass')),
            ],
            options={
                'verbose_name': 'Характеристика класса',
                'verbose_name_plural': 'Характеристики классов',
            },
        ),
        migrations.CreateModel(
            name='ClassAutomationRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.TextField(verbose_name='Требование')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='Обязательное')),
                ('regulation', models.CharField(blank=True, max_length=200, verbose_name='Норматив')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.automationlevel')),
                ('object_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_requirements', to='objects.objectclass')),
            ],
            options={
                'verbose_name': 'Требование автоматизации класса',
                'verbose_name_plural': 'Требования автоматизации классов',
            },
        ),
        migrations.CreateModel(
            name='ObjectCharacteristicValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200, verbose_name='Значение')),
                ('measurement_date', models.DateField(blank=True, null=True, verbose_name='Дата измерения')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.classcharacteristic')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristic_values', to='objects.object')),
            ],
            options={
                'verbose_name': 'Значение характеристики объекта',
                'verbose_name_plural': 'Значения характеристик объектов',
                'ordering': ['object', 'characteristic'],
                'indexes': [models.Index(fields=['object', 'characteristic'], name='objects_obj_object__ea1e9d_idx'), models.Index(fields=['measurement_date'], name='objects_obj_measure_50aaf4_idx'), models.Index(fields=['characteristic', 'value'], name='objects_obj_charact_e6f6b1_idx')],
                'unique_together': {('object', 'characteristic')},
            },
        ),
        migrations.AddIndex(
            model_name='objectclass',
            index=models.Index(fields=['code'], name='objects_obj_code_16cb8f_idx'),
        ),
        migrations.AddIndex(
            model_name='objectclass',
            index=models.Index(fields=['name'], name='objects_obj_name_77ed80_idx'),
        ),
        migrations.AddIndex(
            model_name='objectclass',
            index=models.Index(fields=['parent'], name='objects_obj_parent__0b1ddb_idx'),
        ),
        migrations.AddIndex(
            model_name='object',
            index=models.Index(fields=['hierarchy_level'], name='objects_obj_hierarc_540303_idx'),
        ),
        migrations.AddIndex(
            model_name='object',
            index=models.Index(fields=['status'], name='objects_obj_status_2b28bd_idx'),
        ),
        migrations.AddIndex(
            model_name='object',
            index=models.Index(fields=['object_class'], name='objects_obj_object__d7feb7_idx'),
        ),
        migrations.AddIndex(
            model_name='object',
            index=models.Index(fields=['short_name'], name='objects_obj_short_n_3e55de_idx'),
        ),
        migrations.AddIndex(
            model_name='object',
            index=models.Index(fields=['hierarchy_level', 'status'], name='obj_level_status_idx'),
        ),
        migrations.AddIndex(
            model_name='object',
            index=models.Index(fields=['parent_id', 'hierarchy_level'], name='obj_parent_level_idx'),
        ),
        migrations.AddIndex(
            model_name='object',
            index=models.Index(fields=['legal_entity', 'hierarchy_level'], name='obj_legal_level_idx'),
        ),
        migrations.AddIndex(
            model_name='object',
            index=models.Index(fields=['object_class', 'start_year'], name='obj_class_year_idx'),
        ),
        migrations.AddIndex(
            model_name='object',
            index=models.Index(fields=['technology'], name='obj_technology_idx'),
        ),
        migrations.AddIndex(
            model_name='classcharacteristic',
            index=models.Index(fields=['object_class', 'is_required'], name='objects_cla_object__09a684_idx'),
        ),
        migrations.AddIndex(
            model_name='classcharacteristic',
            index=models.Index(fields=['code'], name='objects_cla_code_0edda8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classcharacteristic',
            unique_together={('object_class', 'code')},
        ),
        migrations.AddIndex(
            model_name='classautomationrequirement',
            index=models.Index(fields=['object_class', 'is_mandatory'], name='objects_cla_object__42cad2_idx'),
        ),
        migrations.AddIndex(
            model_name='classautomationrequirement',
            index=models.Index(fields=['level', 'is_mandatory'], name='objects_cla_level_i_f9a62b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classautomationrequirement',
            unique_together={('object_class', 'level')},
        ),
    ]
