# Generated by Django 6.0.5 on 2026-07-02 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0003_alter_category_options'),
        ('entities', '0001_initial'),
        ('owners', '0001_initial'),
        ('system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Полное название объекта')),
                ('object_short_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Короткое название объекта')),
                ('object_old_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Историческое название объекта')),
                ('object_law_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Юридическое название объекта')),
                ('object_class', models.CharField(blank=True, default='', help_text='Завод, цех, очередь, установка', max_length=255, verbose_name='Классификация объекта')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')])),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата ввода в эксплуатацию')),
                ('is_reconstructed', models.BooleanField(default=False, verbose_name='Была реконструкция')),
                ('capacity', models.CharField(blank=True, default='', max_length=255, verbose_name='Мощность / объём производства')),
                ('status', models.CharField(choices=[('active', 'В эксплуатации'), ('in_project', 'В проекте'), ('reconstruction', 'Реконструкция'), ('stopped', 'Остановлен')], default='active', max_length=50, verbose_name='Состояние объекта')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Дополнительная информация')),
                ('country', models.CharField(blank=True, default='', max_length=255, verbose_name='Страна')),
                ('region', models.CharField(blank=True, default='', max_length=255, verbose_name='Регион')),
                ('city', models.CharField(blank=True, default='', max_length=255, verbose_name='Город')),
                ('street', models.CharField(blank=True, default='', max_length=255, verbose_name='Улица')),
                ('house', models.CharField(blank=True, default='', help_text='Адрес производства (уровень 1)', max_length=255, verbose_name='Дом')),
                ('title', models.CharField(blank=True, default='', help_text='Адрес/расположение установки внутри цеха (только уровень 3)', max_length=255, verbose_name='Кодовое расположение')),
                ('fias_code', models.CharField(blank=True, default='', max_length=255, verbose_name='Код ФИАС')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_objects', to='categories.category')),
                ('creator_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('owner_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_objects', to='owners.ownerentity', verbose_name='Юридическое лицо')),
                ('parent', models.ForeignKey(blank=True, limit_choices_to={'is_deleted': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='objects.object')),
            ],
            options={
                'verbose_name': 'Объект производства',
                'verbose_name_plural': 'Объекты производства',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ObjectSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', 'Планируется'), ('active', 'В эксплуатации'), ('maintenance', 'Обслуживание'), ('decommissioned', 'Выведена из эксплуатации')], default='planned', max_length=50, verbose_name='Статус')),
                ('implementation_date', models.DateField(blank=True, null=True, verbose_name='Дата ввода в эксплуатацию')),
                ('implimentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='implemented_object_systems', to='entities.entity', verbose_name='Исполнитель внедрения')),
                ('integrator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrated_object_systems', to='entities.entity', verbose_name='Интегратор')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.object', verbose_name='Объект')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.automatedsystem', verbose_name='Система')),
            ],
            options={
                'verbose_name': 'Система на объекте',
                'verbose_name_plural': 'Системы на объектах',
                'unique_together': {('object', 'system')},
            },
        ),
    ]
