# Generated by Django 6.0.5 on 2026-07-09 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='object',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='objects.object'),
        ),
    ]
