# Generated by Django 6.0.5 on 2026-06-07 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_objects', to='categories.category'),
        ),
    ]
