# Generated by Django 6.0.5 on 2026-06-11 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_object_category'),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', 'Планируется'), ('active', 'В эксплуатации'), ('maintenance', 'Обслуживание'), ('decommissioned', 'Выведена из эксплуатации')], default='planned', max_length=50, verbose_name='Статус')),
                ('implementation_date', models.DateField(blank=True, null=True, verbose_name='Дата ввода в эксплуатацию')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.object', verbose_name='Объект')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.automatedsystem', verbose_name='Система')),
            ],
            options={
                'verbose_name': 'Система на объекте',
                'verbose_name_plural': 'Системы на объектах',
                'unique_together': {('object', 'system')},
            },
        ),
    ]
