# Generated by Django 6.0.5 on 2026-07-09 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_remove_object_is_deleted_alter_object_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='object',
            options={'ordering': ['hierarchy_level', 'object_name'], 'verbose_name': 'Объект производства', 'verbose_name_plural': 'Объекты производства'},
        ),
        migrations.RenameField(
            model_name='object',
            old_name='level',
            new_name='hierarchy_level',
        ),
        migrations.RenameField(
            model_name='object',
            old_name='name',
            new_name='object_name',
        ),
        migrations.RenameField(
            model_name='object',
            old_name='parent',
            new_name='parent_object',
        ),
        migrations.RenameField(
            model_name='objectsystem',
            old_name='implimentor',
            new_name='implementor',
        ),
    ]
