# Generated by Django 6.0.5 on 2026-06-11 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_objectsystem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='created_by',
            new_name='creator_id',
        ),
    ]
