# Generated by Django 6.0.5 on 2026-07-14 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_rename_creator_id_object_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='fias_code',
        ),
    ]
