# Generated by Django 6.0.5 on 2026-06-22 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_object_owner_entity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='object',
            options={'ordering': ['level', 'name'], 'verbose_name': 'Объект производства', 'verbose_name_plural': 'Объекты производства'},
        ),
    ]
