# Generated by Django 6.0.5 on 2026-07-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_remove_object_fias_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Титульный номер объекта (уровни 2 и 3)', max_length=255, verbose_name='Титульный номер'),
        ),
    ]
