# Generated by Django 6.0.5 on 2026-07-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0006_alter_object_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectsystem',
            name='status',
            field=models.CharField(choices=[('planned', 'Планируется'), ('active', 'В эксплуатации'), ('maintenance', 'Обслуживание'), ('decommissioned', 'Не эксплуатируется')], default='planned', max_length=50, verbose_name='Статус'),
        ),
    ]
