# Generated by Django 6.0.5 on 2026-06-22 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0006_alter_object_options'),
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectsystem',
            name='implimentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='implemented_object_systems', to='participants.participant', verbose_name='Исполнитель внедрения'),
        ),
        migrations.AddField(
            model_name='objectsystem',
            name='integrator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrated_object_systems', to='participants.participant', verbose_name='Интегратор'),
        ),
    ]
