# Generated by Django 6.0.5 on 2026-06-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0007_objectsystem_implimentor_objectsystem_integrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='capacity',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Мощность / объём производства'),
        ),
        migrations.AddField(
            model_name='object',
            name='city',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='object',
            name='country',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='object',
            name='fias_code',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Код ФИАС'),
        ),
        migrations.AddField(
            model_name='object',
            name='house',
            field=models.CharField(blank=True, default='', help_text='Адрес производства (уровень 1)', max_length=255, verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='object',
            name='is_reconstructed',
            field=models.BooleanField(default=False, verbose_name='Была реконструкция'),
        ),
        migrations.AddField(
            model_name='object',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Дополнительная информация'),
        ),
        migrations.AddField(
            model_name='object',
            name='object_class',
            field=models.CharField(blank=True, default='', help_text='Завод, цех, очередь, установка', max_length=255, verbose_name='Классификация объекта'),
        ),
        migrations.AddField(
            model_name='object',
            name='object_law_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Юридическое название объекта'),
        ),
        migrations.AddField(
            model_name='object',
            name='object_old_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Историческое название объекта'),
        ),
        migrations.AddField(
            model_name='object',
            name='object_short_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Короткое название объекта'),
        ),
        migrations.AddField(
            model_name='object',
            name='region',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='object',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата ввода в эксплуатацию'),
        ),
        migrations.AddField(
            model_name='object',
            name='status',
            field=models.CharField(choices=[('active', 'В эксплуатации'), ('in_project', 'В проекте'), ('reconstruction', 'Реконструкция'), ('stopped', 'Остановлен')], default='active', max_length=50, verbose_name='Состояние объекта'),
        ),
        migrations.AddField(
            model_name='object',
            name='street',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Улица'),
        ),
        migrations.AddField(
            model_name='object',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Адрес/расположение установки внутри цеха (только уровень 3)', max_length=255, verbose_name='Кодовое расположение'),
        ),
        migrations.AlterField(
            model_name='object',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Полное название объекта'),
        ),
    ]
