# Generated by Django 6.0.5 on 2026-07-20 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0009_alter_fullcyclefunctioncompetency_industry_and_more'),
        ('objects', '0007_alter_objectsystem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectsystem',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Кто поставил систему на объект: поставщик или вендор полного цикла (можно указать вендора продукта флагом «Поставляется вендором»).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_object_systems', to='entities.entity', verbose_name='Поставщик'),
        ),
    ]
