# Generated by Django 6.0.5 on 2026-07-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0008_objectsystem_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='licensor',
            field=models.CharField(blank=True, default='', help_text='Лицензиар технологии (только для объектов 3-го уровня)', max_length=255, verbose_name='Лицензиар'),
        ),
    ]
